version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:14
    environment:
      - POSTGRES_USER=testusr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jousdb
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: jous-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_ENV=docker
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint:
      - /app/backend/scripts/docker_script.sh

volumes:
  flask-app-db:
    name: flask-app-db
