# Our docker-compose file uses Dockerfile-dev instead of Dockerfile
FROM python:3.8

COPY . /app
WORKDIR /app
ENV PYTHONPATH=/app
RUN pip install -r requirements.txt

ENV FLASK_ENV=docker
EXPOSE 5000
RUN chmod +x /app/backend/scripts/docker_script.sh
