version: '3.7'

services:
  backend:
    container_name: jous-Backend
    build:
      context: .
      dockerfile: ./BackDockerfile
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    entrypoint:
      - /app/docker_script.sh
  frontend:
    container_name: jous-Frontend
    build:
      context: .
      dockerfile: ./FrontDockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - "backend"