// Hand-curated question lists. Question text is a snapshot of the live database
// (export 2026-07-11); each entry links to the canonical /question/<id> page.
// Curated 2026-08-31 by reading the full set of 1,671 questions.

export const curatedLists = {
  "/lists/deep-questions": {
    path: "/lists/deep-questions",
    title: "Deep Questions to Ask — 28 Hand-Picked Cards | Jous",
    description: "28 deep questions to ask, hand-picked from 1,700 open-source conversation cards. No icebreaker filler — questions people actually sit with.",
    keywords: "deep questions to ask, deep conversation questions, meaningful questions, thought provoking questions",
    h1: "Deep Questions, Hand-Picked",
    lede: "Out of 1,700 cards in the open Jous set, these 28 go the deepest without turning the evening into therapy. Draw them one at a time; do not rush.",
    navLabel: "Deep Questions, Hand-Picked",
    count: 28,
    questions: [
      {"id": 194, "text": "What's the closest thing to magic for you?", "note": "The single best opener in the whole set. Nobody has a rehearsed answer."},
      {"id": 49, "text": "If you could ask one question from anyone in the world and they would answer as honest as they can, what would it be?"},
      {"id": 2005, "text": "What’s your most honest answer to the question: “What do you want?”"},
      {"id": 601, "text": "What important truth do very few people agree with you on?"},
      {"id": 628, "text": "Do you regret your words more or your silences?", "note": "A question that quietly sorts a whole table into two camps."},
      {"id": 1990, "text": "What’s a story you tell yourself that you know might not be true?", "note": "Sit with the silence after this one."},
      {"id": 1991, "text": "What part of your worldview are you most afraid to be wrong about?"},
      {"id": 158, "text": "Do you have someone who would always tell you the truth?"},
      {"id": 641, "text": "Who is one person who really saw you, while you did not expect them to?"},
      {"id": 984, "text": "How often do you really see other the person, and let them in return really see you? (once a week, month, year, 10 years, life, never)"},
      {"id": 893, "text": "Who can answer “how is it like to be you?” the best?"},
      {"id": 28, "text": "What is the lie you tell yourself most often?"},
      {"id": 40, "text": "How has your expectation of people to be without flaws changed, with age?"},
      {"id": 143, "text": "What is a practice that brings meaning to your life, but it doesn’t include suffering first?"},
      {"id": 177, "text": "When was the last time you *almost* gave up, but you were happy you did not?"},
      {"id": 279, "text": "What was a context where someone else believed in you before yourself?"},
      {"id": 286, "text": "What was the last time your definition of \"good life\" radically changed?"},
      {"id": 444, "text": "When was the last era in your life where you could achieve unfiltered expression of joy or enthusiasm?"},
      {"id": 720, "text": "What is an experience you have missed the most?"},
      {"id": 782, "text": "Is there any guilt that you thought you would not be able to live with, but in fact you did?"},
      {"id": 1017, "text": "Which event divides your life best into two parts?"},
      {"id": 1425, "text": "Have you ever hidden a central thing in your life, but that to hide it you had to tell many more lies about other things and skip having many further conversations?"},
      {"id": 1469, "text": "What makes being you really hard?"},
      {"id": 1584, "text": "Where in your life do you feel necessary and where do feel completely unnecessary?"},
      {"id": 1609, "text": "What legacy do you hope to leave behind?"},
      {"id": 1997, "text": "What is something you think about every day but rarely say out loud?"},
      {"id": 2023, "text": "What do you wish was not true about you?"},
      {"id": 1739, "text": "What was a void you could recently not fill with material things?"},
    ],
  },
  "/lists/questions-for-couples": {
    path: "/lists/questions-for-couples",
    title: "Questions for Couples — 28 Cards That Are Not Homework | Jous",
    description: "28 hand-picked questions for couples: honest, sometimes uncomfortable, never scripted. From the open-source Jous conversation-card set.",
    keywords: "questions for couples, couples questions, relationship questions, date night questions, questions to ask your partner",
    h1: "Questions for Couples",
    lede: "Not the 'deepen your bond in 5 steps' kind. These 28 cards ask what couples actually wonder and rarely say. Some are tender, some have teeth.",
    navLabel: "Questions for Couples",
    count: 28,
    questions: [
      {"id": 551, "text": "Who can break your heart?"},
      {"id": 644, "text": "In how many of your relationships did you like your partner more than they liked themselves?", "note": "The most quietly devastating relationship question in the deck."},
      {"id": 460, "text": "What would be the most probable cause of break up if you dated yourself?", "note": "Works even better on a first date than in year five."},
      {"id": 461, "text": "What would be your first feeling if your partner broke up with you?"},
      {"id": 668, "text": "If you could ask the opinion of your future self (3 years or 30 years) about your current relationship, would you?"},
      {"id": 989, "text": "How many times do you think your partner was on verge of breaking up with you?"},
      {"id": 1103, "text": "In which of your relationships were you most forgiving of your partner‘s faults?", "note": "Good for couples who think they have already talked about everything."},
      {"id": 1033, "text": "Is your current relationship getting better with time? Is that a must for you in a relationship, or should it rather be stable"},
      {"id": 1099, "text": "Is your partner a better person than you?"},
      {"id": 1122, "text": "Do you think about your beloved every hour that you’re awake? Or almost every."},
      {"id": 1137, "text": "In which way do you like to be like your partner?"},
      {"id": 1160, "text": "Who was the partner you were least frequently angry with?"},
      {"id": 927, "text": "For which of your past and present partners have you had the most respect?"},
      {"id": 939, "text": "Which side of you is your partner unaware of?"},
      {"id": 945, "text": "Do you wonder if your partner would be better off without you?"},
      {"id": 977, "text": "What can you tell your friend but not your partner?"},
      {"id": 708, "text": "Do you feel a part of a change that is happening in micro increments?"},
      {"id": 552, "text": "Have you said I-love-you while you didn’t mean it?"},
      {"id": 128, "text": "Have you ever loved someone without having have told them?"},
      {"id": 491, "text": "After you know you want to spend the rest of your life with someone, how long do you think you will wait to tell them that?"},
      {"id": 423, "text": "Who have you loved most selflessly?"},
      {"id": 578, "text": "Whose marriage do you envy/admire?"},
      {"id": 604, "text": "Do you allow yourself to hate (if for limited time) your partner or your close friends? do you allow then to hate you?"},
      {"id": 1301, "text": "Is love a skill to you?"},
      {"id": 1422, "text": "What is a notable origin story you have with a friend or partner?"},
      {"id": 2014, "text": "What’s the most meaningful non-verbal habit or ritual you share with someone you love?"},
      {"id": 1982, "text": "Have you received unconditional love?"},
      {"id": 1726, "text": "In what way could you possibly drive your (potential) partner crazy and ruin their life?"},
    ],
  },
  "/lists/questions-to-ask-friends": {
    path: "/lists/questions-to-ask-friends",
    title: "Questions to Ask Friends — 28 Cards Past Small Talk | Jous",
    description: "28 hand-picked questions to ask friends, from the open-source Jous card set. About the friendship itself — who maintains it, who gets tough love, who you would start a company with.",
    keywords: "questions to ask friends, questions for friends, friendship questions, deep questions for friends",
    h1: "Questions to Ask Friends",
    lede: "Most friend questions are party filler. These 28 are about the friendship itself: who does the maintaining, who gets your honesty, and which friendships live in the grey area.",
    navLabel: "Questions to Ask Friends",
    count: 28,
    questions: [
      {"id": 1392, "text": "Who knows you the best?"},
      {"id": 302, "text": "which you have already, and which you need now the most? Zameel – someone you have a nodding acquaintance with. Jalees – someone you’re comfortable sitting with for a period of time. Sameer – you have good conversation with them. Nadeem – a drinking companion (just tea) that you might call when you’re free. Sahib – someone who’s concerned for your wellbeing. Rafeeq – someone you can depend upon. You’d probably go on holiday with them. Sadeeq – a true friend, someone who doesn’t befriend you for an ulterior motive. Khaleel – an intimate friend, someone whose presence makes you happy. Anees – someone with whom you’re really comfortable and familiar. Najiyy – a confidant, someone you trust deeply. Safiyy – your best friend, someone you’ve chosen over other friends. Qareen – someone who’s inseparable from you.", "note": "Twelve Arabic words for friend, from nodding acquaintance to inseparable. Sort your people."},
      {"id": 923, "text": "Who \"can\" give you tough love? Who \"does\"? Who do you \"wish\" did more?", "note": "Three answers, usually three different names."},
      {"id": 869, "text": "With which person or group of people have you had most of your laughs in your life?"},
      {"id": 870, "text": "Do you have a friend with whom you share such a deep understanding of humor that it becomes hard to ever talk seriously to them?"},
      {"id": 1497, "text": "Who makes you better?"},
      {"id": 176, "text": "Who among your friends do you feel most needed by?"},
      {"id": 432, "text": "Do you have a friend that you are afraid to lose, as soon as the current activity, which brings you together, ends?"},
      {"id": 438, "text": "How many people are you not sure you are really friends with? to rephrase, how many people do you have in the grey area of friendship?"},
      {"id": 1044, "text": "Who thinks they are your friend, but you are unsure if they are?"},
      {"id": 941, "text": "who was the last friend you made? Are you building a friendship right now?"},
      {"id": 942, "text": "Who was the last friend you lost?"},
      {"id": 1813, "text": "With which friend of yours you should probably break up but you hesitate?", "note": "The question everyone has thought and nobody has said."},
      {"id": 2057, "text": "In your friendships which ones are solely maintained by your effort, which only by their effort, and which are a joint effort to keep it alive? How does each of those feel? Are you thinking about ending some? Are you afraid to be alone if you do? Have you talked about any of them?"},
      {"id": 2470, "text": "Where are you currently being a bad friend?"},
      {"id": 550, "text": "If you consider yourself a work-in-progress, do you have close friends who do not think the same about themselves?"},
      {"id": 613, "text": "What common fear among your friends, you do not have?"},
      {"id": 656, "text": "Which of your friends sends the least number of signals?"},
      {"id": 674, "text": "Where in your day to day life do you wish to see more women/men in?"},
      {"id": 932, "text": "Who were you surprised to learn you can rely on?"},
      {"id": 459, "text": "Who has made exclusive effort for you to be able to know them?"},
      {"id": 427, "text": "Do you have enough friends now? if not when was the last time you did have enough?"},
      {"id": 310, "text": "Who is your cheesiest friend whom you still enjoy hanging with?"},
      {"id": 22, "text": "Who is the most generous person you know, and any hypothesis why they are so?"},
      {"id": 974, "text": "Which of your friends is most suited to co-found a company with you?"},
      {"id": 1668, "text": "How many people you know would fulfil the following: ‚you would not be embarrassed to joint them uninvited for a drink if you met them at a bar‘ ?"},
      {"id": 3016, "text": "Who is the most fun to do projects with?"},
      {"id": 1429, "text": "What makes you feel close to someone?"},
    ],
  },
  "/lists/funny-weird-questions": {
    path: "/lists/funny-weird-questions",
    title: "Funny & Weird Questions — 26 Cards With Loose Screws | Jous",
    description: "26 funny and weird questions from the open-source Jous card set: browser histories, clones, fractals, and whether God can dance.",
    keywords: "funny questions to ask, weird questions, random funny questions, strange questions, questions that make you think",
    h1: "Funny & Weird Questions",
    lede: "The cards that make the set feel alive. Some are jokes with a trapdoor — you start laughing and land somewhere real.",
    navLabel: "Funny & Weird Questions",
    count: 26,
    questions: [
      {"id": 3, "text": "If there was tiny tiny probability that every night you slept you would wake up being a child or a teenage. Would that fact excite you or terrify you, or what?"},
      {"id": 21, "text": "X axis is your age, Y axis is how much you take yourself seriously, how does the diagram look like?"},
      {"id": 97, "text": "What is the strangest thing you have seen in someone else’s house?"},
      {"id": 148, "text": "You could have a kiss with the movie star of your choice, and you could pick the time too. When would you like to have the kiss?"},
      {"id": 178, "text": "You are dying in 10 minutes, you are in your bed with your family around. How much of the 10 minutes do you think you be making jokes?", "note": "Dark, and then everyone laughs anyway."},
      {"id": 213, "text": "Was there any situation where you could have used a clone of yourself?"},
      {"id": 214, "text": "Have you had an epic exit?"},
      {"id": 270, "text": "What is the most stupid thing you have done just out of curiosity?"},
      {"id": 314, "text": "Is a fractal more a complex or more a simple thing?"},
      {"id": 363, "text": "Do you think you think you are funnier as you really are?"},
      {"id": 368, "text": "What is the oldest thing you have seen, and oldest thing you own?"},
      {"id": 417, "text": "Who/what is the imaginary character or work of art that you wished could really be real/alive?"},
      {"id": 418, "text": "Do you have a memory of an animal surprising you?"},
      {"id": 478, "text": "What is your favorite conspiracy theory?"},
      {"id": 481, "text": "What is the funniest moment in your life so far?"},
      {"id": 549, "text": "What is the worst thing someone has seen in your browser history?"},
      {"id": 676, "text": "Do you have the feeling that you are becoming a more or less inspiring person as you grow up/old?", "note": "Yes, that is the whole question."},
      {"id": 780, "text": "Would you have preferred day was divided to 20 hours instead of 24?"},
      {"id": 867, "text": "have you ever perceived humor in animals?"},
      {"id": 902, "text": "Do you like massive rooms, or cosy rooms?"},
      {"id": 924, "text": "If you were to invent a new word for an emotion, what would it be?"},
      {"id": 1459, "text": "What would you be if you were an animal? Why?"},
      {"id": 1737, "text": "Is God (or god) a good dancer?", "note": "Argue about theology through choreography."},
      {"id": 2208, "text": "If your phone was a person, what would it be telling you now?"},
      {"id": 2216, "text": "Do you think animals or pets judge humans or eachother?"},
      {"id": 2731, "text": "Do you talk to plants?"},
    ],
  },
  "/lists/getting-to-know-someone-questions": {
    path: "/lists/getting-to-know-someone-questions",
    title: "Getting to Know Someone — 28 Questions Beyond the Résumé | Jous",
    description: "28 hand-picked getting-to-know-you questions that skip the job-and-hometown script. From the open-source Jous conversation-card set.",
    keywords: "getting to know you questions, questions to get to know someone, icebreaker questions, first date questions",
    h1: "Questions for Getting to Know Someone",
    lede: "Nobody was ever truly known through 'what do you do?'. These 28 cards find the person behind the résumé — their acquired tastes, their soundtrack, what they could lecture on for ten minutes unprepared.",
    navLabel: "Questions for Getting to Know Someone",
    count: 28,
    questions: [
      {"id": 996, "text": "My looks aside, how old would you take me to be based on actions/discussions/mindset/life style/ beliefs/ attitudes?", "note": "Nine likes from the community, the highest in the whole set."},
      {"id": 1458, "text": "What can you give a presentation on for 5 or 10 minutes without any preparation?", "note": "The best party question in the set. Everyone has one topic; finding it is the game."},
      {"id": 11, "text": "What acquired taste do you have?"},
      {"id": 17, "text": "When was the last time you were surprised?"},
      {"id": 55, "text": "What are your guilty pleasures?"},
      {"id": 78, "text": "What is a song that has been one of your favorites the longest?"},
      {"id": 99, "text": "What is the last risk you took?"},
      {"id": 120, "text": "Which parts of your character very few people have uncovered?"},
      {"id": 126, "text": "Would the soundtrack of your life have a fixed or dominant genre? If so what?"},
      {"id": 137, "text": "What are some things not worth trying once to you?"},
      {"id": 200, "text": "what is the simplest melody that you do not get tired of?"},
      {"id": 212, "text": "what are some things that have taken over your life at least for a while, and you were really happy they did?"},
      {"id": 441, "text": "Who was the best host you ever had?"},
      {"id": 445, "text": "What was your best restaurant experience?"},
      {"id": 448, "text": "For what do you count yourself lucky?"},
      {"id": 471, "text": "Which city was very welcoming for walking?"},
      {"id": 594, "text": "What are you serious about that most people are not?"},
      {"id": 639, "text": "Who is the most magical person you know?"},
      {"id": 792, "text": "What do you enjoy so much that you lose track of time?"},
      {"id": 1146, "text": "Do you often listen to sad music?"},
      {"id": 1253, "text": "What is the closest thing in your life to having a religion?", "note": "Works on the religious and the unreligious alike."},
      {"id": 1448, "text": "a new part of life stats. what do you pack for your journey?"},
      {"id": 1467, "text": "What is a repetition that you treasure?"},
      {"id": 1485, "text": "About what in your life do you often wonder “How did I get here?” ?"},
      {"id": 1610, "text": "What’s one travel experience that changed your perspective?"},
      {"id": 1755, "text": "What is something unusual you take with you when traveling?"},
      {"id": 2043, "text": "What’s something “radical” about you?"},
      {"id": 2217, "text": "What is your favourite orosensation? (how food feels in your mouth)"},
    ],
  },
  "/lists/self-reflection-questions": {
    path: "/lists/self-reflection-questions",
    title: "Self-Reflection Questions — 28 Cards to Ask Yourself | Jous",
    description: "28 self-reflection and journaling questions, hand-picked from the open-source Jous card set. For notebooks, long walks, and honest company.",
    keywords: "self reflection questions, journaling questions, journal prompts, questions to ask yourself, introspective questions",
    h1: "Self-Reflection Questions",
    lede: "Cards you can draw alone. Good in a journal, better on a long walk, best with one person who will not let you get away with a polished answer.",
    navLabel: "Self-Reflection Questions",
    count: 28,
    questions: [
      {"id": 571, "text": "Are you a friend to yourself?", "note": "The whole self-help aisle, compressed into five words."},
      {"id": 1457, "text": "Are you as kind to yourself as you are to others?"},
      {"id": 802, "text": "What are you currently trying to unlearn?"},
      {"id": 629, "text": "Do you have something to prove currently?"},
      {"id": 664, "text": "What did you last put considerable effort into but proved impossible?"},
      {"id": 671, "text": "What comes to you in waves?"},
      {"id": 730, "text": "What is your favourite flavour of shit sandwich? (The hardship you are glad to do)", "note": "Everyone has a favourite hardship. Naming it is oddly relaxing."},
      {"id": 748, "text": "Are you afraid your best work is behind you?"},
      {"id": 883, "text": "How important is humility in your interactions?"},
      {"id": 948, "text": "What do you wish you had not taken personally, or as a reflection of you?"},
      {"id": 1004, "text": "What grownup thing are you still failing to do or understand?"},
      {"id": 1285, "text": "When do you wish you were harder on yourself?"},
      {"id": 1287, "text": "What would you write about in a letter to your future self? Why?"},
      {"id": 1445, "text": "What are some of your „I know about it, I am not going to do anything about it“ sort of issues?"},
      {"id": 1454, "text": "How often do you feel shame and judgment towards your feelings and fight against feeling them, rather than accepting your feeling as neutral?"},
      {"id": 1471, "text": "Did you ever stop picturing yourself as if you were inside a race with all other people? If yes, when?"},
      {"id": 1549, "text": "Do you think it is selfish to devote most of your time and attention to becoming a better version of yourself?"},
      {"id": 1664, "text": "What is an identity you accepted for yourself that stopped you from growing, but that you no longer believe about yourself? maybe something like I am \"not decisive\""},
      {"id": 1665, "text": "Has your self-compassion decreased or increased with age? if it has increased, what is the best consequence you have felt from it?"},
      {"id": 1722, "text": "Can you go one week without ever looking at your wounds, shortcomings and weaknesses?"},
      {"id": 1748, "text": "What is a compliment you don’t hear enough, if you would not be honest but really honest?"},
      {"id": 1831, "text": "What would you do if you were guaranteed success and you could not fail at it?"},
      {"id": 1832, "text": "What would you do if you were guaranteed to fail no matter what you choose? What would be most worth doing even without a chance of success?", "note": "The inverse of the famous version, and much more honest."},
      {"id": 2001, "text": "What’s a conversation you keep having with yourself?"},
      {"id": 2205, "text": "What do you wish you could stop judging yourself for?"},
      {"id": 2290, "text": "What did you start too late?"},
      {"id": 2329, "text": "How much is the victim/agent balance of your story?"},
      {"id": 2617, "text": "What has been your biggest second chance?"},
    ],
  },
  "/lists/family-questions": {
    path: "/lists/family-questions",
    title: "Questions to Ask Family — 22 Cards for the People Who Raised You | Jous",
    description: "22 hand-picked questions for parents, siblings, and family dinners — about permission, praise, Sundays, and the roles that outlive childhood. From the open-source Jous set.",
    keywords: "questions to ask family, questions to ask your parents, family conversation starters, family dinner questions",
    h1: "Questions to Ask Your Family",
    lede: "The people who know you longest often know you least in words. These 22 cards are for dinner tables, long drives, and the one visit a year where a real conversation might fit.",
    navLabel: "Questions to Ask Your Family",
    count: 22,
    questions: [
      {"id": 127, "text": "Do you find your parents interesting? Is that new or was it always so"},
      {"id": 201, "text": "Who is the most emotional person in your family?"},
      {"id": 479, "text": "How do you think your family has influenced your sense of humor?"},
      {"id": 722, "text": "What do your parents do that is creative?"},
      {"id": 723, "text": "In the family that you grew up in, how established was the need to ask permission to do what you wanted to do?"},
      {"id": 724, "text": "Who do your parents let, to tell them what to do?"},
      {"id": 725, "text": "What do you wish you did not ask permission for?"},
      {"id": 950, "text": "Growing up did you hear more praise or more discouragement from your parents and environment?"},
      {"id": 970, "text": "Do/Did you believe your mom could have done better than your dad?", "note": "Ask only when everyone is ready to be honest."},
      {"id": 999, "text": "Who never told you no when you were a kid?"},
      {"id": 1417, "text": "What is something you thought your parents would never understand but they did?"},
      {"id": 1419, "text": "What is one thing you wish your parents would understand?"},
      {"id": 1433, "text": "What role did your parents play in the relationship you ended up having with your siblings?"},
      {"id": 1548, "text": "What do you wish your parents would have valued, as you were growing up?"},
      {"id": 1594, "text": "How have your family influenced your resilience?"},
      {"id": 1595, "text": "Was your childhood and treatment while growing up the same your other siblings?"},
      {"id": 1601, "text": "How much do the environments in which your parents grew up differ from your own?"},
      {"id": 2180, "text": "When did you have to be a parent figure for your parents?"},
      {"id": 2603, "text": "What did your family do on Sundays, or on the nearest equivalent of a Sunday?"},
      {"id": 2923, "text": "What is something you once believed because it was normal in your family?"},
      {"id": 2928, "text": "In your family, what role do people still invite you to play? The difficult one, the clever one, the selfish one, the helper, the child, the dramatic one, the successful one, the unstable one, the reasonable one.", "note": "Family roles outlive childhood. Naming yours is step one."},
      {"id": 3047, "text": "How did forgiveness process look like in your childhood home?"},
    ],
  },
};

export const curatedListLinks = Object.values(curatedLists).map((l) => ({
  href: l.path,
  label: l.navLabel,
  description: `${l.count} hand-picked cards`, 
}));
